"""v_02_update_product_table

Revision ID: 8ae78e31337f
Revises: ce179003e5be
Create Date: 2024-05-04 12:06:53.162729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae78e31337f'
down_revision: Union[str, None] = 'ce179003e5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    # ### end Alembic commands ###
